FROM ros:humble-perception-jammy
LABEL maintainer="bernd.pfrommer@gmail.com"
LABEL version="1.0"
LABEL description="amd64 jammy/humble image with openeb"
ARG DEBIAN_FRONTEND=noninteractive
ARG ROS2_VERSION=humble

RUN apt-get update

# for add-apt-repository and to make debconf happy
RUN apt-get -y install software-properties-common apt

#
# some additional ROS2 packages
#
#
# some additional ROS2 packages
#
RUN apt-get -y install python3-osrf-pycommon ros-${ROS2_VERSION}-image-transport ros-${ROS2_VERSION}-cv-bridge ros-${ROS2_VERSION}-sensor-msgs ros-${ROS2_VERSION}-std-msgs ros-${ROS2_VERSION}-rosbag2* ros-${ROS2_VERSION}-tf2-ros ros-${ROS2_VERSION}-image-geometry ros-${ROS2_VERSION}-tf2-geometry-msgs ros-${ROS2_VERSION}-camera-info-manager ros-${ROS2_VERSION}-ament-clang-format ros-${ROS2_VERSION}-ament-cmake-clang-format ros-${ROS2_VERSION}-ament-cmake-*

#
# some additional ubuntu packages:
#
RUN apt-get -y install git libopencv-dev

#
# install openeb prerequisites
#

RUN apt-get -y install software-properties-common apt-utils python3-osrf-pycommon libceres-dev python3-wstool iputils-ping wget libcanberra-gtk-module mesa-utils cmake libboost-program-options-dev libeigen3-dev libavcodec58 libavformat58 libswscale5 libswresample3 libavutil56 libusb-1.0-0 libpcre2-16-0 libdouble-conversion3 libxcb-xinput0 libxcb-xinerama0 build-essential unzip curl git libgtest-dev libboost-all-dev libusb-1.0-0-dev libglew-dev libglfw3-dev libcanberra-gtk-module ffmpeg libyaml-cpp-dev

#
# compile openeb from source and install it
#
RUN mkdir /tmp/openeb && cd /tmp/openeb && git clone https://github.com/prophesee-ai/openeb.git && cd openeb && mkdir build && cd build && cmake .. -DCOMPILE_PYTHON3_BINDINGS=OFF -DBUILD_TESTING=OFF && cmake --build . --config Release -- -j 4 && cmake --build . --target install && rm -rf /tmp/openeb
